## To install apache server
---
- name: install apache2 server
  hosts: all
  become: yes
  tasks:
    - name: install apache2
      ansible.builtin.apt:
        name: apache2
        update_cache: yes
        state: present
---

## To install apache server with php
---
- name: install apache2 server
  hosts: all
  become: yes
  tasks:
    - name: install apache2
      ansible.builtin.apt:
        name: apache2
        update_cache: yes
        state: present
    - name: install php
      ansible.builtin.apt:
        name: 
          - php
          - libapache2-mod-php
          - php-mysql
        update_cache: yes
        state: present
    - name: Copy info.php to php path
      ansible.builtin.copy:
        src: info.php
        dest: /var/www/html/info.php