# final
---
- name: install dotnet
  hosts: all
  become: yes
  tasks:
    - name: install url
      ansible.builtin.get_url:
        url: https://packages.microsoft.com/config/ubuntu/20.04/packages-microsoft-prod.deb
        dest: /tmp
    - name: Install a .deb package
      ansible.builtin.apt:
        deb: /tmp/packages-microsoft-prod.deb
    - name: installing dotnet
      ansible.builtin.apt:
        name: dotnet-sdk-7.0
        update_cache: yes
        state: present
---
# trail
---
- name: install dotnet
  hosts: all
  become: yes
  tasks:
    - name: install url
      ansible.builtin.get_url:
        url: https://packages.microsoft.com/config/ubuntu/20.04/packages-microsoft-prod.deb -O packages-microsoft-prod.deb
        dest: /tmp
    - name: Install a .deb package
      ansible.builtin.apt:
        deb: /tmp/packages-microsoft-prod.deb
    # - name: install dotnet packages
    #   ansible.builtin.dpkg_selections:
    #     name: packages-microsoft-prod.deb
    #     selection: install
    - name: installing dotnet
      ansible.builtin.apt:
        name: dotnet-sdk-7.0
        update_cache: yes
        state: present