# Installing java-17
---
- name: install openjdk-17-jdk
  hosts: all
  become: yes
  tasks:
    - name: install java-17
      ansible.builtin.apt:
        name: openjdk-17-jdk
        update_cache: yes
        state: present