---
- name: Install Spring petclinic application
  hosts: all
  become: yes
  tasks:
    - name: Cloning of spc
      ansible.builtin.git:
        repo: https://github.com/srikanthvelma/spring-petclinic.git
        dest: /tmp/spring-petclinic
        clone: yes
        update: no
    - name: install java
      ansible.builtin.apt:
        name: openjdk-17-jdk
        update_cache: yes
        state: present
    - name: install maven
      ansible.builtin.apt:
        name: maven
        update_cache: yes
        state: present
    - name: Create a group 
      ansible.builtin.group:
        name: spring
        state: present
    - name: Create a user 
      ansible.builtin.user:
        name: spring
        create_home: yes
        group: spring
        state: present
    - name: changing directory to repo
      ansible.builtin.file:
        path: /tmp/spring-petclinic
        state: directory
        owner: spring
        group: spring
        recurse: yes
        mode: '0755'
    - name: mvn package
      ansible.builtin.shell:
        chdir: /tmp/spring-petclinic
        cmd: ./mvnw package
    - name: copy the service file
      ansible.builtin.copy:
        content: |
          [Unit]
          Description=The springpetclinic service


          [Service]
          User=spring
          WorkingDirectory=/home/spring/
          ExecStart=/usr/bin/java -jar /tmp/spring-petclinic/target/spring-petclinic-3.0.0-SNAPSHOT.jar
          SuccessExitStatus=101
          TimeoutStopSec=10
          Restart=on-failure
          RestartSec=5


          [Install]
          WantedBy=multi-user.target
        dest: /etc/systemd/system/spc.service
        state: directory
        owner: spring
        group: spring
        recurse: true
        mode: '0755'
        remote_src: yes
    - name: restart spc service
      ansible.builtin.systemd:
        name: spc
        daemon_reload: true
        enabled: true
        state: restarted
